### ISSUE TITLE
Update krew index

### ISSUE THREAD

**Issue by GTB3NW** [profefe/kube-profefe#36]
If I'm understanding krew correctly, we need to update the index to make the newer versions of the client available.

Off the back of the latest release which includes auth updates I think it would be a good idea to update. I did notice the version on krew is not parallel with the version of kprofefe, so might be worth updating that too?

**Comment by gianarb** [comment]
Yep! I am working on a small fix for the kubectl, and with that, I will also build a GitHub action that should keep them in sync "automagically"!

**Comment by GTB3NW** [comment]
@gianarb Superb ty!
